name = "Structured"
uuid = "a64ab3a6-1e61-46d9-9cad-3303c166b426"
authors = ["Per Rutquist <per.rutquist@gmail.com> and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
